name: linux 

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
  workflow_dispatch:

jobs:
  vol-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build automake autoconf libtool libtool-bin
          # hdf5
          git clone https://github.com/HDFGroup/hdf5.git -b hdf5_1_12_1
          # mpi
          sudo apt-get install libopenmpi-dev
          # zlib
          sudo apt-get install zlib1g-dev 
          
      - name: Install HDF5
        run: |
          mydir="$PWD"
          export HDF5_DIR=$mydir/hdf5/install
          mkdir $HDF5_DIR
          cd hdf5
          export HDF5_LIBTOOL=/usr/bin/libtoolize
          ./autogen.sh
          ./configure --prefix=$HDF5_DIR --enable-parallel
          make && make install

      - name: Install
        run: |          
          mydir="$PWD"
          export HDF5_DIR=$mydir/hdf5/install
          export VOL_DIR=$mydir
          cd $VOL_DIR
          autoreconf -fvi
          ./configure --with-hdf5=${HDF5_DIR} --enable-shared --enable-zlib
          make
          
      - name: Test
        run: |
          mydir="$PWD"
          export H5_DIR=$mydir/hdf5
          export VOL_DIR=$mydir/
          export HDF5_DIR=$mydir/hdf5/install
          export LD_LIBRARY_PATH=$VOL_DIR/src:$H5_DIR/install/lib:$LD_LIBRARY_PATH
          export HDF5_PLUGIN_PATH="$VOL_DIR/src"
          export HDF5_VOL_CONNECTOR="LOG under_vol=0;under_info={}"
          cd $mydir
          cd test
          make check
          cat test/basic/test-suite.log
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: test-suite.log
          path: ${{ runner.workspace }}/vol-log-based/test/basic/test-suite.log
