name: Spack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spack
      uses: actions/checkout@v3
    - name: Test Spack
      run: |
        . ./share/spack/setup-env.sh
        spack spec hdf5-vol-log
        spack install hdf5-vol-log
        spack test run hdf5-vol-log  
      