name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up dependencies
          run: |
            sudo apt-get update
            sudo apt-get install automake autoconf libtool libtool-bin m4
            # mpi
            sudo apt-get install mpich
            # zlib
            sudo apt-get install zlib1g-dev        
        - name: Install HDF5
          run: |
            WORKDIR=$(pwd)
            git clone https://github.com/HDFGroup/hdf5.git -b develop hdf5
            cd hdf5
            export HDF5_LIBTOOL=/usr/bin/libtoolize
            ./autogen.sh
            ./configure --prefix=${WORKDIR}/.local/hdf5/develop --enable-hl --enable-parallel --enable-build-mode=production CC=mpicc
            make -j 64
            make -j 64 install
        - name: Test log VOL
          run: |
            WORKDIR=$(pwd)
            autoreconf -i
            ./configure --prefix=${WORKDIR}/.local/logvol --with-hdf5=${WORKDIR}/.local/hdf5/develop --enable-shared
            make -j 64
            make -j 64 tests
            export LD_LIBRARY_PATH=${WORKDIR}/.local/hdf5/develop:$LD_LIBRARY_PATH
            make check
        
