name: Ubuntu_mpich

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up dependencies
          run: |
            sudo apt-get update
            sudo apt-get install automake autoconf libtool libtool-bin m4
            # The MPICH installed on github actions is too slow
            # sudo apt-get install mpich
            # mpicc -v
            # zlib
            sudo apt-get install zlib1g-dev
        - name: Build MPICH
          run: |
            WORKDIR=$(pwd)
            rm -rf ${WORKDIR}/MPICH
            mkdir ${WORKDIR}/MPICH
            cd ${WORKDIR}/MPICH
            wget -q https://www.mpich.org/static/downloads/4.0.2/mpich-4.0.2.tar.gz
            gzip -dc mpich-4.0.2.tar.gz | tar -xf -
            cd mpich-4.0.2
            ./configure --prefix=${WORKDIR}/MPICH \
                        --silent \
                        --enable-romio \
                        --with-file-system=ufs \
                        --with-device=ch3:sock \
                        --enable-fortran \
                        CC=gcc FC=gfortran
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            make -s -j 4 distclean >> qout 2>&1
            cd ${WORKDIR}
        - name: Install HDF5
          run: |
            WORKDIR=$(pwd)
            rm -rf ${WORKDIR}/HDF5
            mkdir ${WORKDIR}/HDF5
            cd ${WORKDIR}/HDF5
            wget -qc https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.13/hdf5-1.13.0/src/hdf5-1.13.0.tar.gz
            tar -zxf hdf5-1.13.0.tar.gz
            cd hdf5-1.13.0
            ./configure --prefix=${WORKDIR}/HDF5 \
                        --silent \
                        --disable-fortran \
                        --disable-tests \
                        --enable-parallel \
                        --enable-build-mode=production \
                        CC=${WORKDIR}/MPICH/bin/mpicc
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            make -s -j 4 distclean >> qout 2>&1
            cd ${WORKDIR}
        - name: Install NetCDF
          run: |
            WORKDIR=$(pwd)
            rm -rf ${WORKDIR}/NetCDF
            mkdir ${WORKDIR}/NetCDF
            cd ${WORKDIR}/NetCDF
            wget -qc https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.7.4.tar.gz
            tar -zxf v4.7.4.tar.gz
            cd netcdf-c-4.7.4
            ./configure --prefix=${WORKDIR}/NetCDF \
                        --silent \
                        --disable-dap \
                        CC=${WORKDIR}/MPICH/bin/mpicc \
                        CPPFLAGS="-I${WORKDIR}/HDF5/include" \
                        LDFLAGS="-L${WORKDIR}//HDF5/lib" \
                        LIBS="-lhdf5"
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            make -s -j 4 distclean >> qout 2>&1
            cd ${WORKDIR}
        - name: Build and test Log-layout based VOL
          run: |
            WORKDIR=$(pwd)
            autoreconf -i
            ./configure --with-hdf5=${WORKDIR}/HDF5 \
                        --enable-test-netcdf4=${WORKDIR}/NetCDF \
                        --enable-test-openpmd \
                        --enable-test-hdf5-iotest \
                        --with-mpi=${WORKDIR}/MPICH
            # Do NOT test QMCPACK, as it requires FFTW which fails to build
            make -j 4
            # Do NOT parallel build, cmake for external tests can fail
            make tests
            make check
            make ptest
            make -j4 -s V=1 LIBTOOLFLAGS=--silent distcheck DISTCHECK_CONFIGURE_FLAGS="--silent --with-hdf5=${WORKDIR}/HDF5 --with-mpi=${WORKDIR}/MPICH"
            cd ${WORKDIR}
        - name: Print log
          if: ${{ always() }}
          run: |
            WORKDIR=$(pwd)
            cat ${WORKDIR}/config.log
            cat ${WORKDIR}/tests/basic/*.log
            cat ${WORKDIR}/tests/dynamic/*.log
            cat ${WORKDIR}/tests/testcases/*.log
            cat ${WORKDIR}/tests/nc4/*.log
            cat ${WORKDIR}/tests/external/hdf5_iotest/*.log
            cat ${WORKDIR}/tests/external/openpmd/*.log
            cat ${WORKDIR}/examples/*.log
            cat ${WORKDIR}/examples/hdf5_examples/*.log
            cat ${WORKDIR}/utils/*/*.log

